image: node:latest

stages:
  - code-testing
  - staging-server
  - acceptance-testing

linting:
  stage: code-testing
  script:
    - npm install
    - npm run linter

unit-testing:
  stage: code-testing
  script:
  - npm install
  - npm test

code-coverage:
  stage: code-testing
  script:
    - npm install
    - npm run coverage

coverage-report:
  stage: staging-server
  script:
    - npm install
    - npm run coverage