image: node:latest

stages:
 - test
 - coverage

lint:
 stage: test
 script:
   - npm install
   - npm run linter

test:
 stage: test
 script:
 - npm install
 - npm test

 coverage:
  stage: coverage
  script:
  - npm install
  - npm run coverage
